<?php
// $Id: random_captcha_type.module,v 1.7 2007/09/25 00:09:14 soxofaan Exp $

/**
 * Implementation of a "meta CAPTCHA" which randomly picks a CAPTCHA type
 */


/**
 * Implementation of hook_help().
 */
function random_captcha_type_help($section) {
  switch ($section) {
    case 'admin/user/captcha/random_captcha_type':
      return '<p>'. t('This CAPTCHA type is a "meta" CAPTCHA type, which randomly picks one of the selected CAPTCHA types.') .'</p>';
  }
}

/**
 * Implementation of hook_menu().
 */
function random_captcha_type_menu($may_cache) {
  $items = array();
  if ($may_cache) {
    // add an administration tab for random_captcha_type
    $items[] = array(
      'path' => 'admin/user/captcha/random_captcha_type',
      'title' => t('Random CAPTCHA type'),
      'callback' => 'drupal_get_form',
      'callback arguments' => array('random_captcha_type_settings_form'),
      'type' => MENU_LOCAL_TASK,
    );
  }
  return $items;
}

/**
 * Function for getting all the possible CAPTCHA types to switch between.
 * For use as #options entry of a checkboxes widget.
 */
function _random_captcha_type_get_all_types() {
  $captcha_types = array();
  foreach (module_implements('captcha') as $module) {
    // skip random_captcha_type module
    if ($module == 'random_captcha_type') {
      continue;
    }
    // get available  types
    $result = module_invoke($module, 'captcha', 'list');
    if (is_array($result)) {
      foreach ($result as $type) {
        $captcha_types["$module/$type"] = "$type ($module)";
      }
    }
  }
  return $captcha_types;
}

/**
 * Function for getting the enabled CAPTCHA types.
 * Alternative of variable_get('random_captcha_type_enabled_types', ...) with
 * sensible default value.
 * For use as #default_value of checkboxes widget.
 * Returns an array mapping "$module/$type" to "$module/$type" for the enabled types
 */
function _random_captcha_type_get_enabled_types() {
  $enabled_types = array();
  $_enabled_types = variable_get('random_captcha_type_enabled_types', NULL);
  if ($_enabled_types === NULL) {
    foreach (_random_captcha_type_get_all_types() as $key => $value) {
      $enabled_types[$key] = $key;
    }
    variable_set('random_captcha_type_enabled_types', $enabled_types);
  }
  else {
    foreach ($_enabled_types as $key => $value) {
      list($module, $type) = explode('/', $value);
      // check if type is still available
      $list = module_invoke($module, 'captcha', 'list');
      if ($list && in_array($type, $list)) {
        $enabled_types[$key] = $value;
      }
    }
  }
  return $enabled_types;
}

/**
 * Configuration form
 */
function random_captcha_type_settings_form() {
  $enabled_types = _random_captcha_type_get_enabled_types();
  if (count($enabled_types) < 2) {
    drupal_set_message(t('You need at least two CAPTCHA types (other than %random_captcha_type).', array('%random_captcha_type' => 'Random CAPTCHA type')), 'error');
  }
  $form = array();
  $captcha_types = _random_captcha_type_get_all_types();
  $form['random_captcha_type_enabled_types'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Randomly switch between'),
    '#options' => $captcha_types,
    '#default_value' => $enabled_types,
  );
  return system_settings_form($form);
}

/**
 * Implementation of form validation
 */
function random_captcha_type_settings_form_validate($form_id, $form_values) {
  if ($form_id == 'random_captcha_type_settings_form') {
    // at least 2 CAPTCHA types should be selected
    if (count(array_filter($form_values['random_captcha_type_enabled_types'])) < 2) {
      form_set_error('random_captcha_type_enabled_types', t('You should select at least two CAPTCHA types.'));
    }
  }
}

/**
 * Implementation of hook_captcha
 */
function random_captcha_type_captcha($op, $captcha_type='') {
  switch ($op) {
    case 'list':
      $enabled_types = _random_captcha_type_get_enabled_types();
      if (count($enabled_types) < 2) {
        return;
      }
      return array('Random CAPTCHA type');
    case 'generate':
      if ($captcha_type == 'Random CAPTCHA type') {
        if (isset($_POST['random_captcha_type'])) {
          // If this is a POST request, we're possibly in a validation phase
          // so the CAPTCHA type should be the same as in the originating form
          $module_and_type = $_POST['random_captcha_type'];
        }
        else {
          // If not, just pick a random one
          $types = _random_captcha_type_get_enabled_types();
          $module_and_type = $types[array_rand($types)];
        }
        list($module, $type) = explode('/', $module_and_type);
        // Call the generate CAPTCHA hook
        $captcha = module_invoke($module, 'captcha', 'generate', $type);
        // Store the current CAPTCHA type so it can be recovered for
        // regenerating the form in the validation phase
        $captcha['form']['random_captcha_type'] = array (
          '#type' => 'hidden',
          '#value' => $module_and_type,
        );
        return $captcha;
      }
  }
}
