<?php
// $Id: drutex.install,v 1.1.2.1 2008/11/17 09:15:36 darthsteven Exp $

/**
 * @file
 * DruTeX Install File.
 */

/* Drutex does not install a module table */

/**
 * Implementation of hook_uninstall().
 */

function drutex_uninstall() {

//  delete all drutex variables in the variable table and clear the variables cache
  db_query("DELETE FROM {variable} WHERE name like 'drutex_%%'");
  cache_clear_all('variables', 'cache');
}


